### PR TITLE
Feature/political geography selection [render preview]

### PR DESCRIPTION
**Pull request by ev-sc**
This is in support of this milestone: https://linear.app/commonknowledge/project/hope-not-hate-organising-map-26db4b988ef8/overview#milestone-3682f403-7b2f-4c34-baff-1183488952c1

- [x]  There's a lot of refactoring to get the map report UI and logic into a better place.
- [x]  A new mapbox tileset for constituencies which allows the full zoom range
- [x]  A new tileset for wards that does the same
- [x]  A selector for switching between geographies

### CODE REVIEW

**Comment by joaquimds** [comment]
Initial reaction: this looks so great! Really amazing refactor.

Unfortunately this MR seems to remove the work Anna did on image upload in the Hub, and I suspect it also removes the design refactor work that Arby had done. Unfortunately, I suspect Arby will have to re-do his changes, as they may not be relevant after the design changes here.

However, I think we do need to re-commit [Anna's work](https://github.com/commonknowledge/mapped/pull/145/files). I can try doing this if it's helpful @ev-sc

**Comment by ev-sc** [comment]
Ah shucks. 😄
Sorry about the broken hub stuff. I just made sure the CI steps were passing but didn't inspect the other parts of the app! 
If you want to work the changes back in I would appreciate it!

**Comment by joaquimds** [comment]
Also, the preview branches are now working, so you can see this branch here: https://meep-intelligence-hub-frontend-pr-143.onrender.com

Username is admin and password is in BW

**Comment by ev-sc** [comment]
Amazing @joaquimds !

**Pull request merged**
