### PR TITLE
Add (hard coded) colour key for events on TCC map

### PR DESCRIPTION
**Pull request by Moggach**
## Description
This PR adds a colour key for the events on the TCC map. It can be updated to reflect new event types and their colours.
It also commits copies of the svg icons to the repo.
N.B. this is hard coded because it's for TCC only and both the hub specific check and the copy is also hard coded

## Motivation and Context
Addresses issue [CC-173](https://linear.app/commonknowledge/issue/CC-173/add-key-for-events-colour-coding-on-map)

## Screenshots (if appropriate):
Untitled

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by conatus** [comment]
Just to note there is more than one hub. There is also Tipping Point's expression of much of this data. So there does need to be some manner of switch here.

**Comment by Moggach** [comment]
> Just to note there is more than one hub. There is also Tipping Point's expression of much of this data. So there does need to be some manner of switch here.

that will apply to everything right? So the copy as well?
I think we need to speak to them about what they want on their Hub post election and take it from there?

**Review by joaquimds — APPROVED** [review]

**Comment by Moggach** [comment]
I'm going to hold off on merging this until TCC have new events to be loaded to the map. Then I'll adjust the icon labels as well.

**Comment by ev-sc** [comment]
@Moggach  Is this PR dead?

**Comment by Moggach** [comment]
> @Moggach Is this PR dead?

yes, I'll close it

**Pull request closed without merging**
